##
# @author Lucas Obitz, Luca-Philipp Grumbach
# @section DESCRIPTION
# Execute tests on GitHub Actions with ASan
##
name: Run Tests (+ ASan)

on: [push, workflow_dispatch]
jobs:
  run-tests-valgrind:
    name: Run Tests (+ ASan)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Compile Tests
        run: |
            make tests-san
      - name: Run Unit Tests
        run: |
            ./build/linux/tests/unit-tests-san
      - name: Run Integration Tests
        run: |
            ./build/linux/tests/int-tests-san