##
# @author Lucas Obitz, Luca-Philipp Grumbach
# @section DESCRIPTION
# Execute tests on GitHub Actions with Valgrind
##
name: Run Tests (+ Valgrind)

on: [push, workflow_dispatch]
jobs:
  run-tests-valgrind:
    name: Run Tests (+ Valgrind)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Compile Tests
        run: |
            make tests
      - name: Run Valgrind
        run: |
            valgrind ./build/linux/tests/unit/tests
      - name: Run Tests
        run: |
            ./build/linux/tests/unit/tests